version: '3.8'

services:
  # autorunpoc:
  #   container_name: autorunpoc
  #   image: docker.pkg.github.com/dev681999/autorunpoc/autorunpoc:latest
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   ports:
  #     - 8090:8090
  #   restart: on-failure

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --http-api --http-api-token ${TOKEN} --trace --debug 
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8000:8080